### PR TITLE
remove location overlay to fix location by network

### PR DESCRIPTION
**Pull request by ygorigor**
Removing this will make the phone to use FusedLocation that I now is working for all

### CODE REVIEW

**Comment by ygorigor** [comment]
Don't close it or merge it now. Lets see  if location will work after this fix https://github.com/AQSD/proprietary_vendor_xiaomi/pull/2/commits/5a3ddfe415a15fb78ee7e6407c4147ad28028124

**Comment by ygorigor** [comment]
I did some tests with com.qualcomm.location. Unfortunately com.qualcomm.location from garlic make the phone to bootloop. With original apk from land location not working in camera and other apps. So please merge this commit.

**Comment by ygorigor** [comment]
I made 2 screen records on build 09.21 and 09.23
09.21
https://drive.google.com/open?id=0B_Aud8jODqVzU29MUkdKcVAyOTg
09.23
https://drive.google.com/open?id=0B_Aud8jODqVzWkI3UWRmeWMzTEU

**Comment by impulsar** [comment]
@ygorigor thanks for your efforts buddy :)

**Comment by danielstuart14** [comment]
we should find a way to use qcom location service. Thx for the effort, but let's try something else.
I saw your commit on vendor, maybe santoni blobs (7.1 blobs) will work.
Thank you!

**Comment by danielstuart14** [comment]
Well, I'll add that just for now.

**Comment by ygorigor** [comment]
@danielstuart14 Maybe overlay shold look like in this commit https://github.com/LineageOS/android_device_motorola_griffin/commit/b3a180574d91f00abcfdc2d89f8c801101a667f9

**Comment by ygorigor** [comment]
And one more. In CAF sources overlay look like this

    <string name="config_comboNetworkLocationProvider" translatable="false">com.qualcomm.location</string>

**Pull request closed without merging**
