### PR TITLE
land: return to stock param.

### PR DESCRIPTION
**Pull request by dasshubham762**

### CODE REVIEW

**Comment by danielstuart14** [comment]
why?

**Comment by dasshubham762** [comment]
Loudspeaker is too loud in call even in lowest volume

**Comment by dasshubham762** [comment]
RX1 value is increased in 2nd patch

**Comment by danielstuart14** [comment]
Even before the commit that increased the speaker volume, the loudspeaker was already too loud. It isn't related to the  mixer_paths volume.

**Comment by dasshubham762** [comment]
Ok sir.

**Pull request closed without merging**
