### PR TITLE
Fix mediaserver sepolicy and add more commits for camera.

### PR DESCRIPTION
**Pull request by ygorigor**
This commits fix camcorder on latest build (I hope)
All credits goes to @nichcream

### CODE REVIEW

**Comment by nichcream** [comment]
Nope. You're still missing a couple of commits to make it work fully.

**Comment by ygorigor** [comment]
Can you point me to the right direction?

**Comment by danielstuart14** [comment]
is it gtg?

**Comment by ygorigor** [comment]
I compiling ROM now with this changes to test. 
I think is gtg but you can wait till I flash new ROM and check.

**Comment by nichcream** [comment]
These commits still not enough to shut people from asking why camcorder hangs at 30s. I moved my device tree away temporarily as I'm still discussing with @Klozz about some stuff. Recommendation is to wait till I sort up the mess and publish tree again.

**Comment by ygorigor** [comment]
I tested this changes. Video don't stop at 30sec but it produce stuttering videos. I think the time is not synchronized between camera and device.

**Comment by ygorigor** [comment]
At least Footej Camera is working well, camera and camcorder.

**Comment by Klozz** [comment]
The correct way is fix the issues with the "stock" camera apps.
In this case daniel works in lineage so the correct way is fix the issue with Snap camera.

**Comment by ygorigor** [comment]
I know, but for now it's a workaround till a solution will be found.

**Comment by nichcream** [comment]
I can only hint that audio has got to do with it. Ups.. revealed too much. :)

**Comment by ygorigor** [comment]
:)

**Comment by ygorigor** [comment]
I know that is related to AAC encoder, I saw it in logcat, but my knowledge is not enough to solve this.

**Pull request closed without merging**
