### PR TITLE
land: Set correct PRODUCT_MANUFACTURER

### PR DESCRIPTION
**Pull request by dasshubham762**

### CODE REVIEW

**Comment by impulsar** [comment]
@dasshubham762, actually wingtech is oem for our device :)

**Comment by dasshubham762** [comment]
[@impulsar ro.product.manufacturer is Xiaomi on stock MIUI.
screenshot_2017-09-27-17-23-56-678_pl solidexplorer2

**Comment by impulsar** [comment]
Obviously they've rebranded it as Xiaomi, but I guess Dan wants to keep things real

**Comment by dasshubham762** [comment]
I think it would be better to keep manufacturer Xiaomi.  I'm reopening this. Let Dan decide what it should be. 😀

**Comment by danielstuart14** [comment]
Well, xiaomi really wants to hide that some of its phones aren't from them. But, actually, or phone is made by Wingtech, as many other redmi devices.
I'm keeping the brand as xiaomi, since this is how everybody knows the phone. But the manufacturer really is wingtech.
Check redmi 2, they did a even more aggressive move: https://github.com/LineageOS/android_device_wingtech_wt88047

**Comment by dasshubham762** [comment]
I knew it and but manufacturer is also Xiaomi in xpe source. And as my opinion keeping it Stock(as MIUI or Mi) might be better. 
Also you can check these links:
Santoni: https://github.com/Wzedlare/android_device_xiaomi_santoni/blob/cm-14.1/
Mido: https://github.com/TheScarastic/android_device_xiaomi_mido

**Pull request closed without merging**
